version: "3.8"
services:
  gif-bot:
    build: .
    container_name: gif-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./stickies.json:/app/stickies.json
    restart: unless-stopped
